# Generated by Django 4.2.1 on 2023-05-23 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Kategori",
            fields=[
                ("id_kategori", models.AutoField(primary_key=True, serialize=False)),
                ("nama_kategori", models.CharField(max_length=255)),
                ("keterangan", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Pengguna",
            fields=[
                ("id_pengguna", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=255)),
                ("nama", models.CharField(max_length=255)),
                (
                    "saldo_transaksi",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Transaksi",
            fields=[
                ("id_transaksi", models.AutoField(primary_key=True, serialize=False)),
                ("tanggal_transaksi", models.DateField()),
                ("jenis_transaksi", models.CharField(max_length=255)),
                ("nominal", models.DecimalField(decimal_places=2, max_digits=10)),
                ("deskripsi", models.TextField(blank=True)),
                (
                    "kategori",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dooit.kategori"
                    ),
                ),
                (
                    "pengguna",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dooit.pengguna"
                    ),
                ),
            ],
        ),
    ]
