# Generated by Django 4.2.1 on 2023-06-01 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Kategori",
            fields=[
                ("id_kategori", models.AutoField(primary_key=True, serialize=False)),
                ("nama_kategori", models.CharField(max_length=255)),
                ("keterangan", models.TextField()),
            ],
            options={
                "ordering": ("id_kategori",),
            },
        ),
        migrations.CreateModel(
            name="Transaksi",
            fields=[
                ("id_transaksi", models.AutoField(primary_key=True, serialize=False)),
                ("tanggal_transaksi", models.DateField()),
                (
                    "jenis_transaksi",
                    models.CharField(
                        choices=[
                            ("pemasukan", "Pemasukan"),
                            ("pengeluaran", "Pengeluaran"),
                        ],
                        max_length=255,
                    ),
                ),
                ("deskripsi", models.TextField(blank=True)),
                ("nominal", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "kategori",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dooit.kategori"
                    ),
                ),
                (
                    "pengguna",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("tanggal_transaksi",),
            },
        ),
        migrations.CreateModel(
            name="Saldo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "saldo",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "pengguna",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("id",),
            },
        ),
    ]
