# Generated by Django 4.2.1 on 2023-05-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dooit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="saldo",
            name="saldo",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
