# Generated by Django 4.2.1 on 2023-05-23 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dooit", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="kategori",
            options={"ordering": ("id_kategori",)},
        ),
        migrations.AlterModelOptions(
            name="pengguna",
            options={"ordering": ("id_pengguna",)},
        ),
        migrations.AlterModelOptions(
            name="transaksi",
            options={"ordering": ("id_transaksi",)},
        ),
    ]
