# Generated by Django 4.2.1 on 2023-05-23 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dooit", "0002_alter_kategori_options_alter_pengguna_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="pengguna",
            name="saldo_transaksi",
        ),
        migrations.AddField(
            model_name="pengguna",
            name="saldo",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="transaksi",
            name="jenis_transaksi",
            field=models.CharField(
                choices=[("pemasukan", "Pemasukan"), ("pengeluaran", "Pengeluaran")],
                max_length=255,
            ),
        ),
    ]
